"""Render the A7 torch-free certification report from the FROZEN artifacts.

Numbers are never hand-typed (R5): every figure — the CPU fingerprints, the
bit-identity verdict, the R anchors, the GPU fail-loud table, the torch version
— is read from artifacts/a7_torchfree/v<ver>/{cpu_slim,cpu_torch,gpu_faillloud}.json.

Usage: python render_report.py   (writes reports/a7-torchfree-certification-v<ver>.md)
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

VER = "4.6.12"
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / "artifacts/a7_torchfree" / f"v{VER}"
OUT = ROOT / "reports" / f"a7-torchfree-certification-v{VER}.md"

_ANCHOR_ATOL = 1e-12


def load(name):
    return json.load(open(ART / name))


def fmt_vec(v):
    return "[" + ", ".join(f"{x:.12g}" if x is not None else "nan" for x in v) + "]"


def main():
    slim = load("cpu_slim.json")
    torch = load("cpu_torch.json")
    gpu = load("gpu_faillloud.json")

    # ---- Verify the load-bearing claims straight from the artifacts ----
    assert slim["torch_present"] is False and torch["torch_present"] is True
    assert slim["py_version"] == VER and torch["py_version"] == VER == gpu["py_version"]
    cpu_identical = slim["cpu"] == torch["cpu"]
    n_sub = len(slim["cpu"])

    anchored = {k: v for k, v in slim["cpu"].items() if "anchor" in v}
    anchor_ok = {
        k: (np.asarray(v["fp"]).shape == np.asarray(v["anchor"]).shape
            and np.allclose(v["fp"], v["anchor"], rtol=0, atol=_ANCHOR_ATOL))
        for k, v in anchored.items()
    }
    all_anchors_ok = all(anchor_ok.values())

    checks = gpu["checks"]
    n_loud = sum(1 for c in checks.values() if c["failed_loud"])
    all_loud = n_loud == len(checks)

    torch_ver = torch["torch_version"]

    P = []
    P.append(f"# A7 torch-free certification — pystatistics v{VER}\n")
    P.append(
        f"> Certifies that the entire **pystatistics v{VER}** corpus (installed from "
        f"**PyPI**) runs **correctly without torch**, and that every explicit "
        f"`backend='gpu'` entry point **fails loud** when no GPU/torch is present. "
        f"Evidence lives in `artifacts/a7_torchfree/v{VER}/`. Generated by "
        f"`render_report.py` from frozen artifacts — **do not edit numbers by "
        f"hand**; fix the artifact or the renderer and re-render.\n")
    P.append(
        "**What A7 requires** (CONVENTIONS.md A7 + A6, RIGOR foundational Guarantee "
        "2): numpy + scipy are the only hard runtime dependencies; **torch is an "
        "optional `[gpu]` extra**. The package must run correctly torch-free — "
        "degradation is *performance only*, never function or correctness — and an "
        "explicit GPU request without a usable GPU/torch must be **disclosed and "
        "fail loud**, never silently served on the CPU.\n")

    P.append("## 1. Environments\n")
    P.append(
        "Two throwaway PyPI environments, identical except for torch:\n\n"
        "| env | install | torch |\n| --- | --- | --- |\n"
        f"| **slim** | `pip install pystatistics=={VER} h5py` | absent "
        f"(`import torch` fails) |\n"
        f"| **with-torch** | `pip install pystatistics=={VER} torch h5py` | "
        f"**{torch_ver}** |\n")

    P.append("## 2. Correctness is torch-independent — CPU fingerprints bit-identical\n")
    P.append(
        f"The driver runs one canonical CPU call per subsystem on fixed, "
        f"deterministic inputs and records a numeric fingerprint of each result. "
        f"The **A7 correctness claim** is that torch changes nothing on the CPU "
        f"path: the fingerprints from the slim and with-torch envs must be "
        f"**byte-for-byte identical**.\n\n"
        f"**Result: {'PASS' if cpu_identical else 'FAIL'} — all {n_sub} subsystem "
        f"fingerprints are bit-identical between the slim and with-torch envs.**\n\n"
        f"Subsystems covered ({n_sub}): "
        + ", ".join(f"`{k}`" for k in sorted(slim["cpu"])) + ".\n")

    P.append("## 3. Non-circularity — fingerprints anchored to R\n")
    P.append(
        f"So the certification is not merely pystatistics agreeing with itself, "
        f"{len(anchored)} fingerprints are anchored to values computed "
        f"independently in R (asserted to `atol={_ANCHOR_ATOL:g}` by the driver, "
        f"which refuses to write an artifact on mismatch):\n\n"
        "| subsystem | fingerprint | R anchor | match |\n| --- | --- | --- | --- |")
    for k in sorted(anchored):
        v = anchored[k]
        P.append(f"| `{k}` | {fmt_vec(v['fp'])} | {fmt_vec(v['anchor'])} | "
                 f"{'✓' if anchor_ok[k] else '✗'} |")
    P.append("")
    P.append(f"**All {len(anchored)} R anchors match.**\n"
             if all_anchors_ok else "**ANCHOR MISMATCH — see table.**\n")

    P.append("## 4. Fidelity — every GPU request fails loud (slim env)\n")
    P.append(
        f"In the torch-free env, each `backend='gpu'` entry point must raise "
        f"(A6/A7: an explicit GPU request that cannot be honored fails loud, never "
        f"a silent CPU fallback).\n\n"
        f"**Result: {n_loud}/{len(checks)} raised"
        f"{' — all loud' if all_loud else ' — SOME NOT LOUD'}.**\n\n"
        "| entry point | raised | exception |\n| --- | --- | --- |")
    for k in checks:
        c = checks[k]
        P.append(f"| `{k}` | {'✓' if c['failed_loud'] else '✗'} | "
                 f"`{c['exc_type'] or '—'}` |")
    P.append("")

    arima_c = checks.get("timeseries.arima[gpu]", {})
    auto_c = checks.get("timeseries.auto_arima[gpu]", {})
    P.append("### Finding A7-1 — `arima` / `auto_arima` GPU silent-CPU, fixed at "
             f"{VER}\n")
    P.append(
        f"This certification pass surfaced one real fidelity defect. Before {VER}, "
        f"`arima(..., backend='gpu')` and `auto_arima(..., backend='gpu')` "
        f"**silently computed on the CPU** and reported `backend_name='cpu'`: their "
        f"exact-ML/CSS-ML/CSS path has no GPU kernel, and the `backend=` argument "
        f"was ignored rather than validated — a silent backend substitution "
        f"(Guarantee-2 / A6 violation). At v4.6.11 this driver recorded "
        f"`timeseries.arima[gpu]` as **not loud**.\n\n"
        f"The fix makes both functions raise on an explicit GPU backend "
        f"(`gpu`/`gpu_fp64`/`mps`/`cuda`) for any method other than `'Whittle'` — "
        f"the one ARIMA method that *does* have a GPU implementation — pointing the "
        f"user to the real GPU paths (`method='Whittle'` with `backend='gpu'`, or "
        f"`arima_batch`) or to `backend='cpu'`. The `Whittle` GPU path and "
        f"`arima_batch` are unchanged; `backend='cpu'`/`None`/`'auto'` fits are "
        f"byte-for-byte unchanged (§2).\n\n"
        f"At {VER} both now fail loud:\n\n"
        f"- `timeseries.arima[gpu]` → `{arima_c.get('exc_type')}`: "
        f"{arima_c.get('msg','')}\n"
        f"- `timeseries.auto_arima[gpu]` → `{auto_c.get('exc_type')}`: "
        f"{auto_c.get('msg','')}\n")

    verdict_ok = cpu_identical and all_anchors_ok and all_loud
    verdict_word = "A7-CERTIFIED" if verdict_ok else "NOT CERTIFIED"
    P.append("## 5. Verdict\n")
    P.append(
        f"pystatistics **v{VER}** is **{verdict_word}** torch-free:\n\n"
        f"- **Correctness torch-independent** — all {n_sub} CPU fingerprints "
        f"bit-identical with and without torch (torch {torch_ver}).\n"
        f"- **Non-circular** — {len(anchored)} fingerprints anchored to R, all "
        f"matching.\n"
        f"- **Fail-loud** — {n_loud}/{len(checks)} GPU entry points raise in the "
        f"slim env, including the A7-1 fix to `arima`/`auto_arima`.\n\n"
        f"The torch-free path is a first-class citizen: correct, non-circular, and "
        f"loud where it cannot honor a request.\n")

    if not verdict_ok:
        raise AssertionError(
            "A7 certification claims not all satisfied — refusing to render a "
            f"passing report. cpu_identical={cpu_identical} "
            f"anchors_ok={all_anchors_ok} all_loud={all_loud}")

    OUT.write_text("\n".join(P) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
