"""Suite 1: Survival analysis tests against R on California Housing."""

import pytest
import numpy as np

from pystatistics.survival import kaplan_meier, survdiff, coxph


class TestKaplanMeier:
    """Kaplan-Meier curve vs R survfit."""

    def test_survival_probabilities(self, california_data, r_results):
        result = kaplan_meier(
            california_data["HouseAge"].values.astype(float),
            california_data["high_value"].values.astype(float),
        )
        r_ref = r_results["kaplan_meier"]

        # Compare at matching time points
        np.testing.assert_allclose(
            result.time, r_ref["time"], rtol=1e-10,
        )
        np.testing.assert_allclose(
            result.survival, r_ref["survival"], rtol=1e-10,
        )

    def test_n_at_risk(self, california_data, r_results):
        result = kaplan_meier(
            california_data["HouseAge"].values.astype(float),
            california_data["high_value"].values.astype(float),
        )
        r_ref = r_results["kaplan_meier"]

        np.testing.assert_allclose(
            result.n_risk, r_ref["n_risk"], rtol=1e-10,
        )

    def test_standard_errors(self, california_data, r_results):
        result = kaplan_meier(
            california_data["HouseAge"].values.astype(float),
            california_data["high_value"].values.astype(float),
        )
        r_ref = r_results["kaplan_meier"]

        np.testing.assert_allclose(
            result.se, r_ref["std_err"], rtol=1e-10,
        )


class TestLogRank:
    """Log-rank test vs R survdiff."""

    def test_statistic_and_p(self, california_data, r_results):
        result = survdiff(
            california_data["HouseAge"].values.astype(float),
            california_data["high_value"].values.astype(float),
            california_data["region"].values,
        )
        r_ref = r_results["logrank"]

        assert result.statistic == pytest.approx(r_ref["statistic"], rel=1e-10)
        assert result.p_value == pytest.approx(r_ref["p_value"], rel=1e-8)


class TestCoxPH:
    """Cox proportional hazards vs R coxph.

    Uses simulated exponential survival data (seed=42, n=500, 2 covariates,
    true beta = [0.5, -0.3]) — the same data generated by run_r_validation.R.
    This is a proper survival process where Cox PH converges correctly.
    """

    def _load_survival_data(self, r_results):
        """Load the simulated survival data saved by the R script.

        R and Python have different RNGs, so we use the SAME data
        (generated by R, saved in fixtures) for both R and Python fits.
        """
        r_ref = r_results["coxph"]
        time = np.array(r_ref["time"])
        event = np.array(r_ref["event"])
        X = np.column_stack([r_ref["x1"], r_ref["x2"]])
        return time, event, X

    def test_coefficients_vs_r(self, california_data, r_results):
        """Cox PH coefficients match R fixture on same survival data."""
        time, event, X = self._load_survival_data(r_results)
        result = coxph(time, event, X)
        r_ref = r_results["coxph"]

        assert result.converged, "Cox PH should converge on well-posed data"
        np.testing.assert_allclose(
            result.coefficients, r_ref["coefficients"],
            rtol=1e-5,
            err_msg="Cox PH coefficients vs R coxph()",
        )

    def test_hazard_ratios_vs_r(self, california_data, r_results):
        time, event, X = self._load_survival_data(r_results)
        result = coxph(time, event, X)
        r_ref = r_results["coxph"]

        np.testing.assert_allclose(
            result.hazard_ratios, r_ref["hazard_ratios"], rtol=1e-5,
        )

    def test_concordance_vs_r(self, california_data, r_results):
        time, event, X = self._load_survival_data(r_results)
        result = coxph(time, event, X)
        r_ref = r_results["coxph"]

        assert result.concordance == pytest.approx(r_ref["concordance"], rel=1e-4)
